# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "cargo" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    # 添加拉取请求的标签
    labels:
      - "dependencies"
    # 允许的更新类型
    open-pull-requests-limit: 10
    # 允许的更新类型
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
    # 自动合并配置
    auto-merge:
      enabled: true
      merge-method: "squash"
