[package]
name = "quake"
version = "2.0.2"
authors = ["360 Quake Team <quake@360.cn>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.10", features = ["blocking", "json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
clap = "2.33.3"
dirs = "4.0.0"
log = "0.4.0"
env_logger = "0.8.2"
ansi_term = "0.12.1"
chrono = "0.4.19"
regex = "1"
ipaddress = "0.1.1"

[profile.release]
lto = true
opt-level = 'z'
codegen-units = 1