name: rust_build

permissions:
  contents: write

on:
  push:
    tags:
      - "v*"

jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"
    steps:
      # ...
      - name: Checkout Code
        uses: actions/checkout@master

      - name: Create Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false

  upload-assets:
    name: "Upload assets"
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@master
      - name: "upload rust binary action"
        uses: taiki-e/upload-rust-binary-action@v1
        with:
          ref: ${{ github.ref }}
          bin: quake
          tar: unix
          zip: windows
          token: ${{ secrets.GITHUB_TOKEN }}
