name: rust_build_test

permissions:
  contents: write

on:
  push:
    branches:
      - "build_test"

jobs:
  tagged-release-test:
    name: "Tagged Release Test"
    runs-on: "ubuntu-latest"
    steps:
      # ...
      - name: Checkout Code
        uses: actions/checkout@master

      - name: Create Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          title: "Rust Build Test"
          prerelease: true

  upload-assets-test:
    name: "Upload assets"
    needs: tagged-release-test
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-latest
          - target: aarch64-apple-darwin
            os: macos-latest
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
          - target: x86_64-apple-darwin
            os: macos-latest
          # Universal macOS binary is supported as universal-apple-darwin.
          - target: universal-apple-darwin
            os: macos-latest
    runs-on: ${{ matrix.os }}
    container:
      resources:
        limits:
          memory: 2GB
    steps:
      - name: Checkout Code
        uses: actions/checkout@master
      - name: "upload rust binary action"
        uses: taiki-e/upload-rust-binary-action@v1
        with:
          ref: refs/tags/latest
          bin: quake
          target: ${{ matrix.target }}
          archive: $bin-$target
          token: ${{ secrets.GITHUB_TOKEN }}
